// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dokonqzplfyurxhgtzzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRva29ucXpwbGZ5dXJ4aGd0enpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMTc3OTAsImV4cCI6MjA3NTg5Mzc5MH0.auneRRM7PGEHxdellW-BZxAUsf7E8uMpVq6GS6q--BU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});